### ISSUE TITLE
部分设备报错java.lang.ClassCastException: org.apache.harmony.xml.dom.TextImpl cannot be cast to org.w3c.dom.Element

### ISSUE THREAD

**Issue by qiusunshine** [uaoan/UaoanDLNA#1]
有设备报错如下：

java.lang.ClassCastException: org.apache.harmony.xml.dom.TextImpl cannot be cast to org.w3c.dom.Element
	at com.eliyar.bfdlna.Services.AVTransportManager$1.onResponse(Unknown Source:74)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by uaoan** [comment]
再试试看

**Comment by uaoan** [comment]
你好，我这边更新了，你试试看
